services:
  frontend:
    build:
      context: frontend/.
    env_file:
      - .env

  backend:
    build:
      context: backend/.
    env_file:
      - .env

  database:
    build:
      context: database/.
    env_file:
      - .env
