# docker-compose.test.yml
services:
  backend:
    build:
      context: backend/.
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    build:
      context: frontend/.
    env_file:
      - .env

  database:
    build:
      context: database/.
    env_file:
      - .env
